spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=7777Emzie
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

server.port=8080

logging.level.org.springframework=INFO
logging.level.com.company.ecommerce=DEBUG

jwt.secret=MadamECommerce2024SecretKeyForJWTTokenGenerationMustBeLongEnough
jwt.expiration=86400000

upload.dir=uploads
